# -*- coding: utf-8 -*-
"""Act1.4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14TLfIKMAkgTsxB_FRObABAFI5sJJdvJp
"""

triangle_area = lambda b, h: 1/2*(h*b)

def test_triangle_area():
  assert triangle_area(1, 2) == 1
  assert triangle_area(3, 4) == 6
  assert triangle_area(5, 6) == 15
  assert triangle_area(7, 8) == 28
  assert triangle_area(1, 0) == 0
  assert triangle_area(0, 1) == 0
  assert triangle_area(9, 10) == 45
test_triangle_area()

def triangle_area(b, h):
    """
    Calculate the area of a triangle.

    Parameters:
    b: The base length of the triangle.
    h: The height of the triangle.

    Returns:
    area: The area of the triangle.
    """
    area = 0.5 * b * h
    return area

def test_triangle_area():
  assert triangle_area(1, 2) == 1
  assert triangle_area(3, 4) == 6
  assert triangle_area(5, 6) == 15
  assert triangle_area(7, 8) == 28
  assert triangle_area(1, 0) == 0
  assert triangle_area(0, 1) == 0
  assert triangle_area(9, 10) == 45
test_triangle_area()

help(triangle_area)